version: '3.8'

services:
  web1:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 app:app
    expose:
      - 5000
    volumes:
      - web_data:/Users/tomashoffer/Documents/Coding-Projects/bvit

  web2:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 app:app
    expose:
      - 5000
    volumes:
      - web_data:/Users/tomashoffer/Documents/Coding-Projects/bvit

  web3:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 app:app
    expose:
      - 5000
    volumes:
      - web_data:/Users/tomashoffer/Documents/Coding-Projects/bvit

  nginx:
    build: ./nginx
    ports:
      - 8081:8081
    depends_on:
      - web1
      - web2
      - web3
    volumes:
      - web_data:/Users/tomashoffer/Documents/Coding-Projects/bvit


volumes:
  web_data:
