version: '3.9'

services:
  web1:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 app:app
    expose:
      - 5000
    volumes:
      - web_data:/Users/tomashoffer/Documents/Coding-Projects/bvit
    cpu_count: 1

  web2:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 app:app
    expose:
      - 5000
    volumes:
      - web_data:/Users/tomashoffer/Documents/Coding-Projects/bvit
    cpu_count: 1

  web3:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 app:app
    expose:
      - 5000
    volumes:
      - web_data:/Users/tomashoffer/Documents/Coding-Projects/bvit
    cpu_count: 1


  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - web1
      - web2
      - web3
    volumes:
      - web_data:/Users/tomashoffer/Documents/Coding-Projects/bvit
    cpu_count: 4

  locust-master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master --config=/mnt/locust/locust.conf
    cpu_count: 1

  locust-worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master
    cpu_count: 1

volumes:
  web_data:
